default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

test:
  <<: *default
  database: itan_test
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost

production:
  primary: &primary_production
    <<: *default
    database: itan_audiobooks_app_production
    username: itan_audiobooks_app
    password: <%= ENV["ITAN_AUDIOBOOKS_APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: itan_audiobooks_app_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: itan_audiobooks_app_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: itan_audiobooks_app_production_cable
    migrations_paths: db/cable_migrate
